name: Lint and Test

on:
  push:
    branches:
      - main

jobs:
    lint_and_test:

        runs-on: ubuntu-latest

        name: __BLANK 3__

        steps:

        - uses: actions/checkout@v3

        - uses: bahmutov/npm-install@v1

        - run: npm run lint

        - run: npm run test